-- Portable bootstrap for the synthetic revolving-credit default MLOps demo.
-- Render with scripts/render_sql.py and review before execution.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS {{DEVELOPER_ROLE}}
  COMMENT = 'Interactive development role for {{PREFIX}}';
CREATE ROLE IF NOT EXISTS {{ENGINEER_ROLE}}
  COMMENT = 'Deployment role for {{PREFIX}}';
CREATE ROLE IF NOT EXISTS {{PROD_OWNER_ROLE}}
  COMMENT = 'Production object owner for {{PREFIX}}';
CREATE ROLE IF NOT EXISTS {{SERVICE_ROLE}}
  COMMENT = 'Non-human execution role for {{PREFIX}}';

GRANT ROLE {{DEVELOPER_ROLE}} TO ROLE {{ENGINEER_ROLE}};
GRANT ROLE {{ENGINEER_ROLE}} TO ROLE {{PROD_OWNER_ROLE}};
GRANT ROLE {{PROD_OWNER_ROLE}} TO ROLE SYSADMIN;
GRANT ROLE {{SERVICE_ROLE}} TO ROLE {{PROD_OWNER_ROLE}};

CREATE WAREHOUSE IF NOT EXISTS {{WAREHOUSE}}
  WAREHOUSE_SIZE = {{WAREHOUSE_SIZE}}
  AUTO_SUSPEND = {{WAREHOUSE_AUTO_SUSPEND}}
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Disposable warehouse for {{PREFIX}}';
ALTER WAREHOUSE {{WAREHOUSE}} SET
  WAREHOUSE_SIZE = {{WAREHOUSE_SIZE}}
  AUTO_SUSPEND = {{WAREHOUSE_AUTO_SUSPEND}}
  AUTO_RESUME = TRUE;

CREATE COMPUTE POOL IF NOT EXISTS {{COMPUTE_POOL}}
  MIN_NODES = {{POOL_MIN_NODES}}
  MAX_NODES = {{POOL_MAX_NODES}}
  INSTANCE_FAMILY = {{POOL_INSTANCE_FAMILY}}
  AUTO_SUSPEND_SECS = {{POOL_AUTO_SUSPEND}}
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Disposable CPU pool for {{PREFIX}} ML workloads';
ALTER COMPUTE POOL {{COMPUTE_POOL}} SET
  MIN_NODES = {{POOL_MIN_NODES}}
  MAX_NODES = {{POOL_MAX_NODES}}
  AUTO_SUSPEND_SECS = {{POOL_AUTO_SUSPEND}}
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS {{DATABASE}}
  COMMENT = 'Disposable revolving-credit default early-warning MLOps environment';
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{RAW_SCHEMA}}
  COMMENT = 'Warehouse source data and delayed revolving-credit outcomes';
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{DEV_SCHEMA}}
  COMMENT = 'Interactive development datasets, experiments, and models';
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{TEST_SCHEMA}}
  COMMENT = 'Future integration-test objects';
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{PROD_SCHEMA}}
  COMMENT = 'Future production-controlled objects';
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{CONTROL_SCHEMA}}
  COMMENT = 'Portable project configuration and future pipeline evidence';
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{FEATURE_STORE_SCHEMA}}
  COMMENT = 'Development Feature Store objects created by the notebooks';

CREATE STAGE IF NOT EXISTS {{DATABASE}}.{{CONTROL_SCHEMA}}.{{RELEASE_STAGE}}
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Immutable release snapshots for {{PREFIX}}';
CREATE STAGE IF NOT EXISTS {{DATABASE}}.{{CONTROL_SCHEMA}}.{{JOB_STAGE}}
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'ML Job payloads for {{PREFIX}}';
CREATE STAGE IF NOT EXISTS {{DATABASE}}.{{CONTROL_SCHEMA}}.{{DAG_STAGE}}
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Task Graph payloads for {{PREFIX}}';

GRANT USAGE ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE, MONITOR ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE, MONITOR ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{PROD_OWNER_ROLE}};
GRANT USAGE, MONITOR ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{SERVICE_ROLE}};
GRANT USAGE, MONITOR ON COMPUTE POOL {{COMPUTE_POOL}} TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE, MONITOR ON COMPUTE POOL {{COMPUTE_POOL}} TO ROLE {{PROD_OWNER_ROLE}};
GRANT USAGE, MONITOR ON COMPUTE POOL {{COMPUTE_POOL}} TO ROLE {{SERVICE_ROLE}};
GRANT EXECUTE TASK ON ACCOUNT TO ROLE {{PROD_OWNER_ROLE}};
GRANT EXECUTE TASK ON ACCOUNT TO ROLE {{SERVICE_ROLE}};

GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{DEV_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{FEATURE_STORE_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{PROD_OWNER_ROLE}};
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{PROD_OWNER_ROLE}};

GRANT CREATE TABLE, CREATE VIEW, CREATE DATASET, CREATE EXPERIMENT, CREATE MODEL
  ON SCHEMA {{DATABASE}}.{{DEV_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT CREATE TABLE, CREATE TAG, CREATE VIEW, CREATE DYNAMIC TABLE
  ON SCHEMA {{DATABASE}}.{{FEATURE_STORE_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT CREATE SERVICE, CREATE TASK, CREATE NOTEBOOK PROJECT, CREATE MODEL MONITOR
  ON ALL SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{ENGINEER_ROLE}};
GRANT CREATE MODEL, CREATE MODEL MONITOR, CREATE TASK, CREATE VIEW, CREATE TABLE
  ON SCHEMA {{DATABASE}}.{{PROD_SCHEMA}} TO ROLE {{PROD_OWNER_ROLE}};
GRANT READ, WRITE ON ALL STAGES IN SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}}
  TO ROLE {{ENGINEER_ROLE}};
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}}
  TO ROLE {{ENGINEER_ROLE}};

USE WAREHOUSE {{WAREHOUSE}};
USE DATABASE {{DATABASE}};
USE SCHEMA {{RAW_SCHEMA}};

CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_ID VARCHAR COMMENT 'Unique customer identifier; primary business key',
  CUSTOMER_SINCE_DATE DATE COMMENT 'Date the customer relationship began',
  REGION_CODE VARCHAR COMMENT 'Operational region code with values NORTH, SOUTH, EAST, or WEST',
  GENERATED_AT TIMESTAMP_NTZ COMMENT 'Timestamp when the source record was generated'
) COMMENT = 'One row per customer with relationship start date and operational region';

INSERT OVERWRITE INTO DIM_CUSTOMER
WITH customers AS (
  SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS CUSTOMER_NUMBER
  FROM TABLE(GENERATOR(ROWCOUNT => {{ACCOUNT_COUNT}}))
)
SELECT
  'CUST-' || LPAD(CUSTOMER_NUMBER::VARCHAR, 7, '0'),
  DATEADD(MONTH, -(18 + MOD(BITAND(HASH(CUSTOMER_NUMBER, {{DATA_SEED}}), 9223372036854775807), 180)),
          '{{FIRST_OBSERVATION_MONTH}}'::DATE),
  CASE MOD(BITAND(HASH(CUSTOMER_NUMBER, {{DATA_SEED}} + 3), 9223372036854775807), 4)
    WHEN 0 THEN 'NORTH'
    WHEN 1 THEN 'SOUTH'
    WHEN 2 THEN 'EAST'
    ELSE 'WEST'
  END,
  '{{AS_OF_DATE}} 00:00:00'::TIMESTAMP_NTZ
FROM customers;

CREATE OR REPLACE TABLE DIM_CREDIT_ACCOUNT (
  ACCOUNT_ID VARCHAR COMMENT 'Unique revolving-credit facility identifier; primary business key',
  CUSTOMER_ID VARCHAR COMMENT 'Customer identifier joining to DIM_CUSTOMER',
  PRODUCT_CODE VARCHAR COMMENT 'Credit product family; REVOLVING_CREDIT for this portfolio',
  ORIGINATION_CHANNEL VARCHAR COMMENT 'Facility origination channel: BRANCH, DIGITAL, or PARTNER',
  OPEN_DATE DATE COMMENT 'Date the revolving-credit facility was opened',
  CLOSE_DATE DATE COMMENT 'Facility closure date; NULL while open',
  ORIGINAL_CREDIT_LIMIT NUMBER(12,2) COMMENT 'Credit limit at origination in account currency units',
  INTEREST_RATE NUMBER(7,5) COMMENT 'Annual contractual interest rate as a decimal fraction',
  BILLING_CYCLE_DAY NUMBER(2,0) COMMENT 'Nominal monthly statement day from 1 through 28',
  ACCOUNT_STATUS VARCHAR COMMENT 'Current facility status as of the configured information cutoff date',
  GENERATED_AT TIMESTAMP_NTZ COMMENT 'Timestamp when the source record was generated'
) COMMENT = 'One row per existing revolving-credit facility and its origination attributes';

INSERT OVERWRITE INTO DIM_CREDIT_ACCOUNT
WITH accounts AS (
  SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS ACCOUNT_NUMBER
  FROM TABLE(GENERATOR(ROWCOUNT => {{ACCOUNT_COUNT}}))
)
SELECT
  'ACCT-' || LPAD(ACCOUNT_NUMBER::VARCHAR, 7, '0'),
  'CUST-' || LPAD(ACCOUNT_NUMBER::VARCHAR, 7, '0'),
  'REVOLVING_CREDIT',
  CASE MOD(BITAND(HASH(ACCOUNT_NUMBER, {{DATA_SEED}} + 5), 9223372036854775807), 3)
    WHEN 0 THEN 'BRANCH'
    WHEN 1 THEN 'DIGITAL'
    ELSE 'PARTNER'
  END,
  DATEADD(MONTH, -(12 + MOD(BITAND(HASH(ACCOUNT_NUMBER, {{DATA_SEED}} + 7), 9223372036854775807), 108)),
          '{{FIRST_OBSERVATION_MONTH}}'::DATE),
  NULL,
  (1500 + MOD(BITAND(HASH(ACCOUNT_NUMBER, {{DATA_SEED}} + 11), 9223372036854775807), 23500))::NUMBER(12,2),
  (0.1099 + MOD(BITAND(HASH(ACCOUNT_NUMBER, {{DATA_SEED}} + 13), 9223372036854775807), 1200) / 10000.0)::NUMBER(7,5),
  (1 + MOD(BITAND(HASH(ACCOUNT_NUMBER, {{DATA_SEED}} + 17), 9223372036854775807), 28))::NUMBER(2,0),
  'OPEN',
  '{{AS_OF_DATE}} 00:00:00'::TIMESTAMP_NTZ
FROM accounts;

CREATE OR REPLACE TABLE FACT_CUSTOMER_FINANCIAL_SNAPSHOT (
  CUSTOMER_ID VARCHAR COMMENT 'Customer identifier joining to DIM_CUSTOMER',
  SNAPSHOT_DATE DATE COMMENT 'Month-start date when the financial estimate was available',
  MONTHLY_INCOME_ESTIMATE NUMBER(12,2) COMMENT 'Estimated monthly income in account currency units, valid at SNAPSHOT_DATE',
  GENERATED_AT TIMESTAMP_NTZ COMMENT 'Timestamp when the source record was generated'
) COMMENT = 'Monthly customer financial estimates; one row per customer and snapshot month';

INSERT OVERWRITE INTO FACT_CUSTOMER_FINANCIAL_SNAPSHOT
WITH months AS (
  SELECT DATEADD(MONTH, MONTH_NUMBER - 12, '{{FIRST_OBSERVATION_MONTH}}'::DATE) AS SNAPSHOT_DATE
  FROM (
    SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS MONTH_NUMBER
    FROM TABLE(GENERATOR(ROWCOUNT => {{FINANCIAL_SNAPSHOT_MONTHS}}))
  )
)
SELECT
  c.CUSTOMER_ID,
  m.SNAPSHOT_DATE,
  (900 + MOD(BITAND(HASH(c.CUSTOMER_ID, YEAR(m.SNAPSHOT_DATE), {{DATA_SEED}} + 19), 9223372036854775807), 9100))::NUMBER(12,2),
  '{{AS_OF_DATE}} 00:00:00'::TIMESTAMP_NTZ
FROM DIM_CUSTOMER c
CROSS JOIN months m;

CREATE OR REPLACE TABLE FACT_ACCOUNT_EVENT (
  EVENT_ID VARCHAR COMMENT 'Unique account-event identifier; primary event key',
  ACCOUNT_ID VARCHAR COMMENT 'Facility identifier joining to DIM_CREDIT_ACCOUNT',
  EVENT_TIMESTAMP TIMESTAMP_NTZ COMMENT 'Timestamp when the account event became effective',
  EVENT_TYPE VARCHAR COMMENT 'Event type such as CREDIT_LIMIT_CHANGE or ACCOUNT_STATUS_CHANGE',
  OLD_VALUE VARCHAR COMMENT 'Value before the event represented as text',
  NEW_VALUE VARCHAR COMMENT 'Value after the event represented as text',
  GENERATED_AT TIMESTAMP_NTZ COMMENT 'Timestamp when the source record was generated'
) COMMENT = 'One row per facility change event, including effective time and before-and-after values';

INSERT OVERWRITE INTO FACT_ACCOUNT_EVENT
SELECT
  'EVT-LIMIT-' || SUBSTR(a.ACCOUNT_ID, 6),
  a.ACCOUNT_ID,
  DATEADD(
    DAY,
    MOD(BITAND(HASH(a.ACCOUNT_ID, {{DATA_SEED}} + 59), 9223372036854775807), 700),
    DATEADD(MONTH, -9, '{{FIRST_OBSERVATION_MONTH}}'::DATE)
  )::TIMESTAMP_NTZ,
  'CREDIT_LIMIT_CHANGE',
  a.ORIGINAL_CREDIT_LIMIT::VARCHAR,
  (a.ORIGINAL_CREDIT_LIMIT * 1.10)::NUMBER(12,2)::VARCHAR,
  '{{AS_OF_DATE}} 00:00:00'::TIMESTAMP_NTZ
FROM DIM_CREDIT_ACCOUNT a
WHERE MOD(BITAND(HASH(a.ACCOUNT_ID, {{DATA_SEED}} + 23), 9223372036854775807), 4) = 0;

CREATE OR REPLACE TABLE FACT_ACCOUNT_DAILY_SNAPSHOT (
  ACCOUNT_ID VARCHAR COMMENT 'Facility identifier joining to DIM_CREDIT_ACCOUNT',
  SNAPSHOT_DATE DATE COMMENT 'Calendar date represented by this end-of-day servicing state',
  OUTSTANDING_BALANCE NUMBER(14,2) COMMENT 'End-of-day drawn principal balance in account currency units',
  CREDIT_LIMIT NUMBER(12,2) COMMENT 'Credit limit effective on SNAPSHOT_DATE',
  AVAILABLE_CREDIT NUMBER(14,2) COMMENT 'Non-negative undrawn credit available on SNAPSHOT_DATE',
  AMOUNT_DUE NUMBER(12,2) COMMENT 'Statement amount due at the latest billing cycle',
  MINIMUM_PAYMENT_DUE NUMBER(12,2) COMMENT 'Minimum contractual payment due',
  DAYS_PAST_DUE NUMBER(4,0) COMMENT 'Consecutive calendar days the facility is past due, capped at 120',
  ARREARS_AMOUNT NUMBER(12,2) COMMENT 'Overdue amount associated with the current delinquency state',
  ACCOUNT_STATUS VARCHAR COMMENT 'Servicing status on SNAPSHOT_DATE: CURRENT, DELINQUENT, or CHARGED_OFF',
  DATA_SCENARIO VARCHAR COMMENT 'Controlled source regime with values STABLE or DRIFT; excluded from model features',
  GENERATED_AT TIMESTAMP_NTZ COMMENT 'Timestamp when the source record was generated'
) COMMENT = 'Daily revolving-credit servicing state; one row per account and calendar date';

INSERT OVERWRITE INTO FACT_ACCOUNT_DAILY_SNAPSHOT
WITH calendar AS (
  SELECT SNAPSHOT_DATE
  FROM (
    SELECT DATEADD(DAY, DAY_NUMBER, DATEADD(MONTH, -12, '{{FIRST_OBSERVATION_MONTH}}'::DATE))
      AS SNAPSHOT_DATE
    FROM (
      SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS DAY_NUMBER
      FROM TABLE(GENERATOR(ROWCOUNT => {{DAILY_HISTORY_DAYS}}))
    )
  )
  WHERE SNAPSHOT_DATE <= '{{AS_OF_DATE}}'::DATE
), account_dates AS (
  SELECT
    a.ACCOUNT_ID,
    a.ORIGINAL_CREDIT_LIMIT,
    d.SNAPSHOT_DATE,
    DATEDIFF(DAY, DATEADD(MONTH, -12, '{{FIRST_OBSERVATION_MONTH}}'::DATE), d.SNAPSHOT_DATE) AS DAY_NUMBER,
    BITAND(HASH(a.ACCOUNT_ID, {{DATA_SEED}} + 29), 9223372036854775807) AS ACCOUNT_HASH,
    IFF(
      MOD(BITAND(HASH(a.ACCOUNT_ID, {{DATA_SEED}} + 31), 9223372036854775807), 100) < 14,
      DATEADD(
        DAY,
        420 + MOD(BITAND(HASH(a.ACCOUNT_ID, {{DATA_SEED}} + 37), 9223372036854775807), 700),
        DATEADD(MONTH, -12, '{{FIRST_OBSERVATION_MONTH}}'::DATE)
      ),
      NULL
    ) AS STRESS_START_DATE
  FROM DIM_CREDIT_ACCOUNT a
  CROSS JOIN calendar d
), delinquency_state AS (
  SELECT
    *,
    IFF(STRESS_START_DATE IS NULL OR SNAPSHOT_DATE < STRESS_START_DATE,
        0, LEAST(120, DATEDIFF(DAY, STRESS_START_DATE, SNAPSHOT_DATE))) AS DAYS_PAST_DUE_RAW,
    ORIGINAL_CREDIT_LIMIT * IFF(
      MOD(BITAND(HASH(ACCOUNT_ID, {{DATA_SEED}} + 23), 9223372036854775807), 4) = 0
      AND SNAPSHOT_DATE >= DATEADD(
        DAY,
        MOD(BITAND(HASH(ACCOUNT_ID, {{DATA_SEED}} + 59), 9223372036854775807), 700),
        DATEADD(MONTH, -9, '{{FIRST_OBSERVATION_MONTH}}'::DATE)
      ),
      1.10,
      1.00
    ) AS EFFECTIVE_LIMIT
  FROM account_dates
), states AS (
  SELECT
    *,
    LEAST(
      1.18,
      GREATEST(
        0.04,
        0.18 + MOD(ACCOUNT_HASH, 4200) / 10000.0
        + 0.025 * SIN(DAY_NUMBER / 30.0)
        + IFF(SNAPSHOT_DATE >= '{{DRIFT_START_DATE}}'::DATE, 0.08, 0)
        + 0.0035 * DAYS_PAST_DUE_RAW
      )
    ) AS UTILISATION
  FROM delinquency_state
)
SELECT
  ACCOUNT_ID,
  SNAPSHOT_DATE,
  (EFFECTIVE_LIMIT * UTILISATION)::NUMBER(14,2),
  EFFECTIVE_LIMIT::NUMBER(12,2),
  GREATEST(EFFECTIVE_LIMIT - EFFECTIVE_LIMIT * UTILISATION, 0)::NUMBER(14,2),
  GREATEST(EFFECTIVE_LIMIT * UTILISATION * 0.08, 25)::NUMBER(12,2),
  GREATEST(EFFECTIVE_LIMIT * UTILISATION * 0.025, 15)::NUMBER(12,2),
  DAYS_PAST_DUE_RAW::NUMBER(4,0),
  IFF(DAYS_PAST_DUE_RAW = 0, 0,
      GREATEST(EFFECTIVE_LIMIT * UTILISATION * 0.025, 15))::NUMBER(12,2),
  CASE
    WHEN DAYS_PAST_DUE_RAW >= 120 THEN 'CHARGED_OFF'
    WHEN DAYS_PAST_DUE_RAW > 0 THEN 'DELINQUENT'
    ELSE 'CURRENT'
  END,
  IFF(SNAPSHOT_DATE >= '{{DRIFT_START_DATE}}'::DATE, 'DRIFT', 'STABLE'),
  '{{AS_OF_DATE}} 00:00:00'::TIMESTAMP_NTZ
FROM states;

CREATE OR REPLACE TABLE FACT_PAYMENT (
  PAYMENT_ID VARCHAR COMMENT 'Unique payment transaction identifier; primary event key',
  ACCOUNT_ID VARCHAR COMMENT 'Facility identifier joining to DIM_CREDIT_ACCOUNT',
  PAYMENT_DATE DATE COMMENT 'Date the payment was posted',
  PAYMENT_AMOUNT NUMBER(12,2) COMMENT 'Posted amount in account currency units; zero for a missed payment',
  PAYMENT_STATUS VARCHAR COMMENT 'Payment result: POSTED, LATE, or MISSED',
  PAYMENT_CHANNEL VARCHAR COMMENT 'Payment channel: DIRECT_DEBIT, DIGITAL, or BRANCH',
  GENERATED_AT TIMESTAMP_NTZ COMMENT 'Timestamp when the source record was generated'
) COMMENT = 'One row per scheduled facility payment event at approximately monthly cadence';

INSERT OVERWRITE INTO FACT_PAYMENT
WITH monthly_due AS (
  SELECT s.*, a.BILLING_CYCLE_DAY
  FROM FACT_ACCOUNT_DAILY_SNAPSHOT s
  JOIN DIM_CREDIT_ACCOUNT a USING (ACCOUNT_ID)
  WHERE DAY(s.SNAPSHOT_DATE) = a.BILLING_CYCLE_DAY
)
SELECT
  'PMT-' || SUBSTR(ACCOUNT_ID, 6) || '-' || TO_CHAR(SNAPSHOT_DATE, 'YYYYMMDD'),
  ACCOUNT_ID,
  SNAPSHOT_DATE,
  CASE
    WHEN DAYS_PAST_DUE >= 30 THEN 0
    WHEN DAYS_PAST_DUE > 0 THEN MINIMUM_PAYMENT_DUE * 0.60
    ELSE GREATEST(MINIMUM_PAYMENT_DUE,
         OUTSTANDING_BALANCE * (0.04 + MOD(BITAND(HASH(ACCOUNT_ID, SNAPSHOT_DATE, {{DATA_SEED}} + 41), 9223372036854775807), 700) / 10000.0))
  END::NUMBER(12,2),
  CASE WHEN DAYS_PAST_DUE >= 30 THEN 'MISSED'
       WHEN DAYS_PAST_DUE > 0 THEN 'LATE' ELSE 'POSTED' END,
  CASE MOD(BITAND(HASH(ACCOUNT_ID, SNAPSHOT_DATE, {{DATA_SEED}} + 43), 9223372036854775807), 3)
    WHEN 0 THEN 'DIRECT_DEBIT' WHEN 1 THEN 'DIGITAL' ELSE 'BRANCH' END,
  '{{AS_OF_DATE}} 00:00:00'::TIMESTAMP_NTZ
FROM monthly_due;

CREATE OR REPLACE TABLE FACT_CUSTOMER_CONTACT (
  CONTACT_ID VARCHAR COMMENT 'Unique customer-contact identifier; primary event key',
  ACCOUNT_ID VARCHAR COMMENT 'Facility identifier joining to DIM_CREDIT_ACCOUNT',
  CONTACT_TIMESTAMP TIMESTAMP_NTZ COMMENT 'Timestamp when the contact occurred',
  CONTACT_DIRECTION VARCHAR COMMENT 'INBOUND or OUTBOUND contact direction',
  CONTACT_REASON VARCHAR COMMENT 'Operational reason for the contact',
  CONTACT_OUTCOME VARCHAR COMMENT 'Recorded result of the contact',
  GENERATED_AT TIMESTAMP_NTZ COMMENT 'Timestamp when the source record was generated'
) COMMENT = 'One row per servicing contact with direction, reason, outcome, and event time';

INSERT OVERWRITE INTO FACT_CUSTOMER_CONTACT
SELECT
  'CON-' || SUBSTR(ACCOUNT_ID, 6) || '-' || TO_CHAR(SNAPSHOT_DATE, 'YYYYMMDD'),
  ACCOUNT_ID,
  DATEADD(HOUR, 10, SNAPSHOT_DATE::TIMESTAMP_NTZ),
  IFF(DAYS_PAST_DUE > 0, 'OUTBOUND', 'INBOUND'),
  IFF(DAYS_PAST_DUE > 0, 'PAYMENT_SUPPORT', 'ACCOUNT_SERVICE'),
  CASE
    WHEN DAYS_PAST_DUE >= 30 AND MOD(BITAND(HASH(ACCOUNT_ID, SNAPSHOT_DATE, {{DATA_SEED}} + 47), 9223372036854775807), 3) = 0
      THEN 'BROKEN_PROMISE'
    WHEN DAYS_PAST_DUE > 0 THEN 'PROMISE_TO_PAY'
    ELSE 'RESOLVED'
  END,
  '{{AS_OF_DATE}} 00:00:00'::TIMESTAMP_NTZ
FROM FACT_ACCOUNT_DAILY_SNAPSHOT
WHERE DAY(SNAPSHOT_DATE) = 15
  AND (DAYS_PAST_DUE > 0
       OR MOD(BITAND(HASH(ACCOUNT_ID, SNAPSHOT_DATE, {{DATA_SEED}} + 53), 9223372036854775807), 20) = 0);

CREATE OR REPLACE TABLE FACT_DEFAULT_EVENT (
  ACCOUNT_ID VARCHAR COMMENT 'Facility identifier joining to DIM_CREDIT_ACCOUNT',
  DEFAULT_DATE DATE COMMENT 'First date the facility reaches the defined default state',
  DEFAULT_REASON VARCHAR COMMENT 'Reason for default; 90_DAYS_PAST_DUE in this dataset',
  DEFAULT_STATUS VARCHAR COMMENT 'Recorded default lifecycle status',
  GENERATED_AT TIMESTAMP_NTZ COMMENT 'Timestamp when the source record was generated'
) COMMENT = 'Zero or one first default event per revolving-credit facility';

INSERT OVERWRITE INTO FACT_DEFAULT_EVENT
SELECT
  ACCOUNT_ID,
  MIN(SNAPSHOT_DATE),
  '90_DAYS_PAST_DUE',
  'DEFAULTED',
  '{{AS_OF_DATE}} 00:00:00'::TIMESTAMP_NTZ
FROM FACT_ACCOUNT_DAILY_SNAPSHOT
WHERE DAYS_PAST_DUE >= 90
GROUP BY ACCOUNT_ID;

UPDATE DIM_CREDIT_ACCOUNT a
SET ACCOUNT_STATUS = latest.ACCOUNT_STATUS
FROM (
  SELECT ACCOUNT_ID, ACCOUNT_STATUS
  FROM FACT_ACCOUNT_DAILY_SNAPSHOT
  QUALIFY ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID ORDER BY SNAPSHOT_DATE DESC) = 1
) latest
WHERE a.ACCOUNT_ID = latest.ACCOUNT_ID;

CREATE OR REPLACE TABLE ACCOUNT_OBSERVATION (
  ACCOUNT_ID VARCHAR COMMENT 'Facility identifier evaluated at an observation date',
  OBSERVATION_DATE DATE COMMENT 'Month-start date at which prediction-time features are retrieved',
  OUTCOME_FINALITY_DATE DATE COMMENT 'Date the forward 90-day outcome window becomes complete',
  DEFAULT_WITHIN_90D NUMBER(1,0) COMMENT 'One when first default occurs after observation and within 90 days',
  OUTCOME_STATUS VARCHAR COMMENT 'FINALISED when the full horizon is observable; otherwise PENDING',
  GENERATED_AT TIMESTAMP_NTZ COMMENT 'Timestamp when the observation record was generated'
) COMMENT = 'One row per at-risk facility and monthly observation date with a delayed 90-day outcome';

INSERT OVERWRITE INTO ACCOUNT_OBSERVATION
WITH months AS (
  SELECT DATEADD(MONTH, MONTH_NUMBER, '{{FIRST_OBSERVATION_MONTH}}'::DATE) AS OBSERVATION_DATE
  FROM (
    SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS MONTH_NUMBER
    FROM TABLE(GENERATOR(ROWCOUNT => {{OBSERVATION_MONTHS}}))
  )
)
SELECT
  a.ACCOUNT_ID,
  m.OBSERVATION_DATE,
  DATEADD(DAY, {{OUTCOME_WINDOW_DAYS}}, m.OBSERVATION_DATE)::DATE,
  IFF(
    DATEADD(DAY, {{OUTCOME_WINDOW_DAYS}}, m.OBSERVATION_DATE) <= '{{AS_OF_DATE}}'::DATE,
    IFF(d.DEFAULT_DATE > m.OBSERVATION_DATE
        AND d.DEFAULT_DATE <= DATEADD(DAY, {{OUTCOME_WINDOW_DAYS}}, m.OBSERVATION_DATE), 1, 0),
    NULL
  ),
  IFF(DATEADD(DAY, {{OUTCOME_WINDOW_DAYS}}, m.OBSERVATION_DATE) <= '{{AS_OF_DATE}}'::DATE,
      'FINALISED', 'PENDING'),
  '{{AS_OF_DATE}} 00:00:00'::TIMESTAMP_NTZ
FROM DIM_CREDIT_ACCOUNT a
CROSS JOIN months m
LEFT JOIN FACT_DEFAULT_EVENT d USING (ACCOUNT_ID)
WHERE d.DEFAULT_DATE IS NULL OR d.DEFAULT_DATE > m.OBSERVATION_DATE;

CREATE OR REPLACE VIEW AVAILABLE_GROUND_TRUTH (
  ACCOUNT_ID COMMENT 'Facility identifier for the labelled observation',
  OBSERVATION_DATE COMMENT 'Prediction observation date',
  OUTCOME_FINALITY_DATE COMMENT 'Date the 90-day label became fully observable',
  DEFAULT_WITHIN_90D COMMENT 'Binary target for first default after observation and within the following 90 days'
) COMMENT = 'Finalised delayed labels only; no prediction-time features are exposed' AS
SELECT ACCOUNT_ID, OBSERVATION_DATE, OUTCOME_FINALITY_DATE, DEFAULT_WITHIN_90D
FROM ACCOUNT_OBSERVATION
WHERE OUTCOME_STATUS = 'FINALISED';

CREATE OR REPLACE VIEW SCORING_POPULATION (
  ACCOUNT_ID COMMENT 'Facility identifier awaiting a finalised outcome',
  OBSERVATION_DATE COMMENT 'Prediction observation date',
  OUTCOME_FINALITY_DATE COMMENT 'Future date when the 90-day outcome becomes final'
) COMMENT = 'At-risk observations whose 90-day outcomes are still pending' AS
SELECT ACCOUNT_ID, OBSERVATION_DATE, OUTCOME_FINALITY_DATE
FROM ACCOUNT_OBSERVATION
WHERE OUTCOME_STATUS = 'PENDING';

USE SCHEMA {{CONTROL_SCHEMA}};

CREATE OR REPLACE TABLE DEMO_CONFIG (
  CONFIG_KEY VARCHAR COMMENT 'Portable configuration key',
  CONFIG_VALUE VARCHAR COMMENT 'Rendered configuration value',
  DESCRIPTION VARCHAR COMMENT 'Meaning and intended use of the setting'
) COMMENT = 'Configuration values used to interpret and reproduce the source records';

INSERT OVERWRITE INTO DEMO_CONFIG
SELECT column1, column2, column3 FROM VALUES
  ('PREFIX', '{{PREFIX}}', 'Safety prefix for account-level objects'),
  ('DATA_SEED', '{{DATA_SEED}}', 'Seed used to reproduce the generated source records'),
  ('AS_OF_DATE', '{{AS_OF_DATE}}', 'Simulated information cutoff'),
  ('OUTCOME_WINDOW_DAYS', '{{OUTCOME_WINDOW_DAYS}}', 'Default outcome window'),
  ('DRIFT_START_DATE', '{{DRIFT_START_DATE}}', 'Start of controlled portfolio drift');

CREATE OR REPLACE TABLE PIPELINE_RUN (
  RUN_ID VARCHAR COMMENT 'Unique future pipeline-run identifier',
  RELEASE_ID VARCHAR COMMENT 'Release identifier associated with the run',
  ENVIRONMENT VARCHAR COMMENT 'Target lifecycle environment',
  STATUS VARCHAR COMMENT 'Run lifecycle status',
  MODEL_NAME VARCHAR COMMENT 'Registered model collection name',
  MODEL_VERSION VARCHAR COMMENT 'Registered model version',
  SOURCE_COMMIT VARCHAR COMMENT 'Repository commit used for execution',
  METRICS VARIANT COMMENT 'Structured run metrics',
  DECISION_EVIDENCE VARIANT COMMENT 'Structured promotion evidence',
  STARTED_AT TIMESTAMP_NTZ COMMENT 'Run start timestamp',
  COMPLETED_AT TIMESTAMP_NTZ COMMENT 'Run completion timestamp'
) COMMENT = 'Reserved evidence table for a future repeatable training phase';

CREATE OR REPLACE TABLE PROMOTION_DECISION (
  DECISION_ID VARCHAR COMMENT 'Unique future promotion-decision identifier',
  RUN_ID VARCHAR COMMENT 'Pipeline run that produced the candidate',
  CANDIDATE_VERSION VARCHAR COMMENT 'Candidate model version considered',
  INCUMBENT_VERSION VARCHAR COMMENT 'Incumbent model version used for comparison',
  DECISION VARCHAR COMMENT 'Promotion decision outcome',
  CHECKS VARIANT COMMENT 'Structured checks supporting the decision',
  DECIDED_BY VARCHAR COMMENT 'Role or user recording the decision',
  DECIDED_AT TIMESTAMP_NTZ COMMENT 'Decision timestamp'
) COMMENT = 'Reserved controlled-promotion evidence for a future phase';

GRANT SELECT ON ALL TABLES IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT SELECT ON ALL VIEWS IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT REFERENCES ON ALL TABLES IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT REFERENCES ON ALL VIEWS IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT SELECT ON FUTURE VIEWS IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT REFERENCES ON FUTURE TABLES IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT REFERENCES ON FUTURE VIEWS IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT VIEW LINEAGE ON ACCOUNT TO ROLE {{DEVELOPER_ROLE}};
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}} TO ROLE {{ENGINEER_ROLE}};
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}} TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{SERVICE_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{SERVICE_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}} TO ROLE {{SERVICE_ROLE}};
GRANT SELECT ON ALL TABLES IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{SERVICE_ROLE}};
GRANT SELECT ON ALL VIEWS IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{SERVICE_ROLE}};
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}} TO ROLE {{SERVICE_ROLE}};

SELECT
  (SELECT COUNT(*) FROM {{DATABASE}}.{{RAW_SCHEMA}}.DIM_CUSTOMER) AS CUSTOMER_COUNT,
  (SELECT COUNT(*) FROM {{DATABASE}}.{{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT) AS ACCOUNT_COUNT,
  (SELECT COUNT(*) FROM {{DATABASE}}.{{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT) AS DAILY_SNAPSHOT_COUNT,
  (SELECT COUNT(*) FROM {{DATABASE}}.{{RAW_SCHEMA}}.FACT_PAYMENT) AS PAYMENT_COUNT,
  (SELECT COUNT(*) FROM {{DATABASE}}.{{RAW_SCHEMA}}.FACT_DEFAULT_EVENT) AS DEFAULT_EVENT_COUNT;

SELECT
  OUTCOME_STATUS,
  COUNT(*) AS OUTCOME_COUNT,
  AVG(DEFAULT_WITHIN_90D) AS DEFAULT_RATE
FROM {{DATABASE}}.{{RAW_SCHEMA}}.ACCOUNT_OBSERVATION
GROUP BY OUTCOME_STATUS
ORDER BY OUTCOME_STATUS;

ALTER WAREHOUSE {{WAREHOUSE}} SUSPEND;
ALTER COMPUTE POOL {{COMPUTE_POOL}} SUSPEND;

SELECT 'BOOTSTRAP_COMPLETE' AS STATUS,
  '{{DATABASE}}' AS DATABASE_NAME,
  '{{AS_OF_DATE}}'::DATE AS SIMULATED_AS_OF_DATE;