USE ROLE ACCOUNTADMIN;
USE WAREHOUSE {{WAREHOUSE}};
USE DATABASE {{DATABASE}};

-- Review declared grains and source coverage.
SELECT 'DIM_CUSTOMER' AS OBJECT_NAME, COUNT(*) AS RECORD_COUNT,
  COUNT(DISTINCT CUSTOMER_ID) AS DISTINCT_KEY_COUNT
FROM {{RAW_SCHEMA}}.DIM_CUSTOMER
UNION ALL
SELECT 'DIM_CREDIT_ACCOUNT', COUNT(*), COUNT(DISTINCT ACCOUNT_ID)
FROM {{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT
UNION ALL
SELECT 'FACT_CUSTOMER_FINANCIAL_SNAPSHOT', COUNT(*),
  COUNT(DISTINCT CUSTOMER_ID || '|' || SNAPSHOT_DATE::VARCHAR)
FROM {{RAW_SCHEMA}}.FACT_CUSTOMER_FINANCIAL_SNAPSHOT
UNION ALL
SELECT 'FACT_ACCOUNT_DAILY_SNAPSHOT', COUNT(*),
  COUNT(DISTINCT ACCOUNT_ID || '|' || SNAPSHOT_DATE::VARCHAR)
FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT
UNION ALL
SELECT 'FACT_PAYMENT', COUNT(*), COUNT(DISTINCT PAYMENT_ID)
FROM {{RAW_SCHEMA}}.FACT_PAYMENT
UNION ALL
SELECT 'FACT_CUSTOMER_CONTACT', COUNT(*), COUNT(DISTINCT CONTACT_ID)
FROM {{RAW_SCHEMA}}.FACT_CUSTOMER_CONTACT
UNION ALL
SELECT 'FACT_ACCOUNT_EVENT', COUNT(*), COUNT(DISTINCT EVENT_ID)
FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_EVENT
UNION ALL
SELECT 'FACT_DEFAULT_EVENT', COUNT(*), COUNT(DISTINCT ACCOUNT_ID)
FROM {{RAW_SCHEMA}}.FACT_DEFAULT_EVENT
UNION ALL
SELECT 'ACCOUNT_OBSERVATION', COUNT(*),
  COUNT(DISTINCT ACCOUNT_ID || '|' || OBSERVATION_DATE::VARCHAR)
FROM {{RAW_SCHEMA}}.ACCOUNT_OBSERVATION
ORDER BY OBJECT_NAME;

-- Daily history must include at least twelve warm-up months before modelling starts.
SELECT MIN(SNAPSHOT_DATE) AS FIRST_DAILY_SNAPSHOT,
  MAX(SNAPSHOT_DATE) AS LAST_DAILY_SNAPSHOT,
  DATEDIFF(DAY, MIN(SNAPSHOT_DATE), '{{FIRST_OBSERVATION_MONTH}}'::DATE)
    AS WARMUP_DAYS,
  COUNT(DISTINCT SNAPSHOT_DATE) AS CALENDAR_DAYS
FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT;

-- Labels must be delayed, censored by the simulated as-of date, and non-trivial.
SELECT OUTCOME_STATUS,
  COUNT(*) AS OUTCOME_COUNT,
  COUNT_IF(DEFAULT_WITHIN_90D = 1) AS DEFAULT_COUNT,
  AVG(DEFAULT_WITHIN_90D) AS DEFAULT_RATE,
  MIN(OBSERVATION_DATE) AS FIRST_OBSERVATION,
  MAX(OBSERVATION_DATE) AS LAST_OBSERVATION,
  MAX(OUTCOME_FINALITY_DATE) AS LATEST_FINALITY_DATE
FROM {{RAW_SCHEMA}}.ACCOUNT_OBSERVATION
GROUP BY OUTCOME_STATUS
ORDER BY OUTCOME_STATUS;

-- Controlled drift should be visible in prediction-time source facts.
SELECT DATA_SCENARIO,
  COUNT(*) AS DAILY_RECORD_COUNT,
  AVG(DIV0(OUTSTANDING_BALANCE, CREDIT_LIMIT)) AS AVG_UTILISATION,
  AVG(DAYS_PAST_DUE) AS AVG_DAYS_PAST_DUE,
  AVG(IFF(ACCOUNT_STATUS = 'DELINQUENT', 1, 0)) AS DELINQUENCY_RATE
FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT
GROUP BY DATA_SCENARIO
ORDER BY DATA_SCENARIO;

-- Every project-created table and column must be documented.
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA IN ('{{RAW_SCHEMA}}', '{{CONTROL_SCHEMA}}')
  AND TABLE_NAME IN (
    'DIM_CUSTOMER', 'DIM_CREDIT_ACCOUNT', 'FACT_CUSTOMER_FINANCIAL_SNAPSHOT',
    'FACT_ACCOUNT_DAILY_SNAPSHOT', 'FACT_PAYMENT', 'FACT_CUSTOMER_CONTACT',
    'FACT_ACCOUNT_EVENT', 'FACT_DEFAULT_EVENT', 'ACCOUNT_OBSERVATION',
    'DEMO_CONFIG', 'PIPELINE_RUN', 'PROMOTION_DECISION'
  )
  AND TABLE_TYPE = 'BASE TABLE'
  AND NULLIF(TRIM(COMMENT), '') IS NULL
ORDER BY TABLE_SCHEMA, TABLE_NAME;

SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA IN ('{{RAW_SCHEMA}}', '{{CONTROL_SCHEMA}}')
  AND TABLE_NAME IN (
    'DIM_CUSTOMER', 'DIM_CREDIT_ACCOUNT', 'FACT_CUSTOMER_FINANCIAL_SNAPSHOT',
    'FACT_ACCOUNT_DAILY_SNAPSHOT', 'FACT_PAYMENT', 'FACT_CUSTOMER_CONTACT',
    'FACT_ACCOUNT_EVENT', 'FACT_DEFAULT_EVENT', 'ACCOUNT_OBSERVATION',
    'DEMO_CONFIG', 'PIPELINE_RUN', 'PROMOTION_DECISION'
  )
  AND NULLIF(TRIM(COMMENT), '') IS NULL
ORDER BY TABLE_SCHEMA, TABLE_NAME, ORDINAL_POSITION;

-- Machine-readable acceptance gate. All checks must pass before notebook work.
WITH checks AS (
  SELECT 'EXPECTED_CUSTOMER_ROWS' AS CHECK_NAME,
    (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.DIM_CUSTOMER) = {{ACCOUNT_COUNT}} AS PASSED
  UNION ALL
  SELECT 'EXPECTED_ACCOUNT_ROWS',
    (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT) = {{ACCOUNT_COUNT}}
  UNION ALL
  SELECT 'EXPECTED_PROJECT_TABLES', COUNT(*) = 12
  FROM INFORMATION_SCHEMA.TABLES
  WHERE ((TABLE_SCHEMA = '{{RAW_SCHEMA}}' AND TABLE_NAME IN (
           'DIM_CUSTOMER', 'DIM_CREDIT_ACCOUNT', 'FACT_CUSTOMER_FINANCIAL_SNAPSHOT',
           'FACT_ACCOUNT_DAILY_SNAPSHOT', 'FACT_PAYMENT', 'FACT_CUSTOMER_CONTACT',
           'FACT_ACCOUNT_EVENT', 'FACT_DEFAULT_EVENT', 'ACCOUNT_OBSERVATION'
         ))
         OR (TABLE_SCHEMA = '{{CONTROL_SCHEMA}}' AND TABLE_NAME IN (
           'DEMO_CONFIG', 'PIPELINE_RUN', 'PROMOTION_DECISION'
         )))
    AND TABLE_TYPE = 'BASE TABLE'
  UNION ALL
  SELECT 'UNIQUE_DIMENSION_KEYS',
    (SELECT COUNT(*) = COUNT(DISTINCT CUSTOMER_ID)
            AND COUNT_IF(CUSTOMER_ID IS NULL) = 0
     FROM {{RAW_SCHEMA}}.DIM_CUSTOMER)
    AND (SELECT COUNT(*) = COUNT(DISTINCT ACCOUNT_ID)
                AND COUNT_IF(ACCOUNT_ID IS NULL) = 0
         FROM {{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT)
  UNION ALL
  SELECT 'ONE_REVOLVING_PRODUCT',
    COUNT(DISTINCT PRODUCT_CODE) = 1 AND MIN(PRODUCT_CODE) = 'REVOLVING_CREDIT'
  FROM {{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT
  UNION ALL
  SELECT 'ACCOUNT_CUSTOMER_RELATIONSHIPS', COUNT_IF(c.CUSTOMER_ID IS NULL) = 0
  FROM {{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT a
  LEFT JOIN {{RAW_SCHEMA}}.DIM_CUSTOMER c USING (CUSTOMER_ID)
  UNION ALL
  SELECT 'UNIQUE_FINANCIAL_KEYS',
    COUNT(*) = COUNT(DISTINCT CUSTOMER_ID, SNAPSHOT_DATE)
    AND COUNT_IF(CUSTOMER_ID IS NULL OR SNAPSHOT_DATE IS NULL) = 0
  FROM {{RAW_SCHEMA}}.FACT_CUSTOMER_FINANCIAL_SNAPSHOT
  UNION ALL
  SELECT 'FINANCIAL_CUSTOMER_RELATIONSHIPS', COUNT_IF(c.CUSTOMER_ID IS NULL) = 0
  FROM {{RAW_SCHEMA}}.FACT_CUSTOMER_FINANCIAL_SNAPSHOT f
  LEFT JOIN {{RAW_SCHEMA}}.DIM_CUSTOMER c USING (CUSTOMER_ID)
  UNION ALL
  SELECT 'UNIQUE_DAILY_KEYS', COUNT(*) = COUNT(DISTINCT ACCOUNT_ID, SNAPSHOT_DATE)
    AND COUNT_IF(ACCOUNT_ID IS NULL OR SNAPSHOT_DATE IS NULL) = 0
  FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT
  UNION ALL
  SELECT 'COMPLETE_DAILY_COVERAGE', COUNT(*) = {{ACCOUNT_COUNT}}
    * (DATEDIFF(DAY, DATEADD(MONTH, -12, '{{FIRST_OBSERVATION_MONTH}}'::DATE),
                       '{{AS_OF_DATE}}'::DATE) + 1)
  FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT
  UNION ALL
  SELECT 'EXACT_DAILY_BOUNDARIES',
    MIN(SNAPSHOT_DATE) = DATEADD(MONTH, -12, '{{FIRST_OBSERVATION_MONTH}}'::DATE)
    AND MAX(SNAPSHOT_DATE) = '{{AS_OF_DATE}}'::DATE
    AND COUNT(DISTINCT SNAPSHOT_DATE) =
      DATEDIFF(DAY, DATEADD(MONTH, -12, '{{FIRST_OBSERVATION_MONTH}}'::DATE),
                      '{{AS_OF_DATE}}'::DATE) + 1
  FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT
  UNION ALL
  SELECT 'DAILY_ROWS_PER_DATE',
    MIN(DAILY_COUNT) = {{ACCOUNT_COUNT}} AND MAX(DAILY_COUNT) = {{ACCOUNT_COUNT}}
  FROM (
    SELECT SNAPSHOT_DATE, COUNT(*) AS DAILY_COUNT
    FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT
    GROUP BY SNAPSHOT_DATE
  )
  UNION ALL
  SELECT 'EXACT_FINANCIAL_MONTH_COVERAGE',
    MIN(SNAPSHOT_DATE) = DATEADD(MONTH, -12, '{{FIRST_OBSERVATION_MONTH}}'::DATE)
    AND MAX(SNAPSHOT_DATE) = DATEADD(MONTH, {{OBSERVATION_MONTHS}} - 1,
                                     '{{FIRST_OBSERVATION_MONTH}}'::DATE)
    AND COUNT(DISTINCT SNAPSHOT_DATE) = {{FINANCIAL_SNAPSHOT_MONTHS}}
    AND COUNT(*) = {{ACCOUNT_COUNT}} * {{FINANCIAL_SNAPSHOT_MONTHS}}
  FROM {{RAW_SCHEMA}}.FACT_CUSTOMER_FINANCIAL_SNAPSHOT
  UNION ALL
  SELECT 'EXACT_OBSERVATION_MONTH_COVERAGE',
    MIN(OBSERVATION_DATE) = '{{FIRST_OBSERVATION_MONTH}}'::DATE
    AND MAX(OBSERVATION_DATE) <= DATEADD(MONTH, {{OBSERVATION_MONTHS}} - 1,
                                         '{{FIRST_OBSERVATION_MONTH}}'::DATE)
    AND COUNT(DISTINCT OBSERVATION_DATE) = {{OBSERVATION_MONTHS}}
  FROM {{RAW_SCHEMA}}.ACCOUNT_OBSERVATION
  UNION ALL
  SELECT 'UNIQUE_OBSERVATION_KEYS',
    COUNT(*) = COUNT(DISTINCT ACCOUNT_ID, OBSERVATION_DATE)
    AND COUNT_IF(ACCOUNT_ID IS NULL OR OBSERVATION_DATE IS NULL) = 0
  FROM {{RAW_SCHEMA}}.ACCOUNT_OBSERVATION
  UNION ALL
  SELECT 'DAILY_ACCOUNT_RELATIONSHIPS', COUNT_IF(a.ACCOUNT_ID IS NULL) = 0
  FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT s
  LEFT JOIN {{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT a USING (ACCOUNT_ID)
  UNION ALL
  SELECT 'EVENT_ACCOUNT_RELATIONSHIPS',
    (SELECT COUNT_IF(a.ACCOUNT_ID IS NULL)
     FROM {{RAW_SCHEMA}}.FACT_PAYMENT f
     LEFT JOIN {{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT a USING (ACCOUNT_ID)) = 0
    AND (SELECT COUNT_IF(a.ACCOUNT_ID IS NULL)
         FROM {{RAW_SCHEMA}}.FACT_CUSTOMER_CONTACT f
         LEFT JOIN {{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT a USING (ACCOUNT_ID)) = 0
    AND (SELECT COUNT_IF(a.ACCOUNT_ID IS NULL)
         FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_EVENT f
         LEFT JOIN {{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT a USING (ACCOUNT_ID)) = 0
    AND (SELECT COUNT_IF(a.ACCOUNT_ID IS NULL)
         FROM {{RAW_SCHEMA}}.FACT_DEFAULT_EVENT f
         LEFT JOIN {{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT a USING (ACCOUNT_ID)) = 0
  UNION ALL
  SELECT 'OBSERVATION_ACCOUNT_RELATIONSHIPS', COUNT_IF(a.ACCOUNT_ID IS NULL) = 0
  FROM {{RAW_SCHEMA}}.ACCOUNT_OBSERVATION o
  LEFT JOIN {{RAW_SCHEMA}}.DIM_CREDIT_ACCOUNT a USING (ACCOUNT_ID)
  UNION ALL
  SELECT 'VALID_BALANCE_STATE', COUNT_IF(
    OUTSTANDING_BALANCE IS NULL OR CREDIT_LIMIT IS NULL OR AVAILABLE_CREDIT IS NULL
    OR DAYS_PAST_DUE IS NULL OR ARREARS_AMOUNT IS NULL
    OR OUTSTANDING_BALANCE < 0 OR CREDIT_LIMIT <= 0 OR AVAILABLE_CREDIT < 0
    OR DAYS_PAST_DUE < 0 OR DAYS_PAST_DUE > 120 OR ARREARS_AMOUNT < 0
  ) = 0
  FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT
  UNION ALL
  SELECT 'UNIQUE_EVENT_KEYS',
    (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.FACT_PAYMENT)
      = (SELECT COUNT(DISTINCT PAYMENT_ID) FROM {{RAW_SCHEMA}}.FACT_PAYMENT)
    AND (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.FACT_CUSTOMER_CONTACT)
      = (SELECT COUNT(DISTINCT CONTACT_ID) FROM {{RAW_SCHEMA}}.FACT_CUSTOMER_CONTACT)
    AND (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_EVENT)
      = (SELECT COUNT(DISTINCT EVENT_ID) FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_EVENT)
  UNION ALL
  SELECT 'EVENT_POPULATIONS_EXIST',
    (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.FACT_PAYMENT) > 0
    AND (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.FACT_CUSTOMER_CONTACT) > 0
    AND (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_EVENT) > 0
    AND (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.FACT_DEFAULT_EVENT) > 0
  UNION ALL
  SELECT 'ONE_FIRST_DEFAULT_PER_ACCOUNT', COUNT(*) = COUNT(DISTINCT ACCOUNT_ID)
  FROM {{RAW_SCHEMA}}.FACT_DEFAULT_EVENT
  UNION ALL
  SELECT 'DEFAULT_EVENTS_MATCH_90_DPD', COUNT_IF(s.ACCOUNT_ID IS NULL) = 0
  FROM {{RAW_SCHEMA}}.FACT_DEFAULT_EVENT d
  LEFT JOIN {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT s
    ON d.ACCOUNT_ID = s.ACCOUNT_ID
   AND d.DEFAULT_DATE = s.SNAPSHOT_DATE
   AND s.DAYS_PAST_DUE = 90
  UNION ALL
  SELECT 'FINALISED_AND_PENDING_EXIST',
    COUNT_IF(OUTCOME_STATUS = 'FINALISED') > 0
    AND COUNT_IF(OUTCOME_STATUS = 'PENDING') > 0
  FROM {{RAW_SCHEMA}}.ACCOUNT_OBSERVATION
  UNION ALL
  SELECT 'FINALISED_LABELS_RESPECT_AS_OF',
    COUNT_IF(
      OUTCOME_STATUS = 'FINALISED'
      AND (OUTCOME_FINALITY_DATE IS NULL
           OR OUTCOME_FINALITY_DATE > '{{AS_OF_DATE}}'::DATE
           OR DEFAULT_WITHIN_90D IS NULL)
    ) = 0
  FROM {{RAW_SCHEMA}}.ACCOUNT_OBSERVATION
  UNION ALL
  SELECT 'PENDING_LABELS_ARE_NULL',
    COUNT_IF(
      OUTCOME_STATUS = 'PENDING'
      AND (DEFAULT_WITHIN_90D IS NOT NULL
           OR OUTCOME_FINALITY_DATE IS NULL
           OR OUTCOME_FINALITY_DATE <= '{{AS_OF_DATE}}'::DATE)
    ) = 0
  FROM {{RAW_SCHEMA}}.ACCOUNT_OBSERVATION
  UNION ALL
  SELECT 'TARGET_MATCHES_DEFAULT_EVENTS', COUNT_IF(
    o.DEFAULT_WITHIN_90D IS DISTINCT FROM IFF(
      d.DEFAULT_DATE > o.OBSERVATION_DATE
      AND d.DEFAULT_DATE <= o.OUTCOME_FINALITY_DATE, 1, 0)
  ) = 0
  FROM {{RAW_SCHEMA}}.ACCOUNT_OBSERVATION o
  LEFT JOIN {{RAW_SCHEMA}}.FACT_DEFAULT_EVENT d USING (ACCOUNT_ID)
  WHERE o.OUTCOME_STATUS = 'FINALISED'
  UNION ALL
  SELECT 'IMBALANCED_NONTRIVIAL_TARGET',
    AVG(DEFAULT_WITHIN_90D) BETWEEN 0.01 AND 0.25
  FROM {{RAW_SCHEMA}}.ACCOUNT_OBSERVATION
  WHERE OUTCOME_STATUS = 'FINALISED'
  UNION ALL
  SELECT 'STABLE_AND_DRIFT_EXIST', COUNT(DISTINCT DATA_SCENARIO) = 2
  FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT
  UNION ALL
  SELECT 'CONTROLLED_DRIFT_IS_VISIBLE',
    AVG(IFF(DATA_SCENARIO = 'DRIFT', DIV0(OUTSTANDING_BALANCE, CREDIT_LIMIT), NULL))
      > AVG(IFF(DATA_SCENARIO = 'STABLE', DIV0(OUTSTANDING_BALANCE, CREDIT_LIMIT), NULL))
  FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT
  UNION ALL
  SELECT 'SCENARIO_BOUNDARY_MATCHES_CONFIG', COUNT_IF(
    (SNAPSHOT_DATE < '{{DRIFT_START_DATE}}'::DATE AND DATA_SCENARIO != 'STABLE')
    OR (SNAPSHOT_DATE >= '{{DRIFT_START_DATE}}'::DATE AND DATA_SCENARIO != 'DRIFT')
    OR DATA_SCENARIO IS NULL
  ) = 0
  FROM {{RAW_SCHEMA}}.FACT_ACCOUNT_DAILY_SNAPSHOT
  UNION ALL
  SELECT 'TABLE_COMMENTS_COMPLETE', COUNT(*) = 0
  FROM INFORMATION_SCHEMA.TABLES
  WHERE TABLE_SCHEMA IN ('{{RAW_SCHEMA}}', '{{CONTROL_SCHEMA}}')
    AND TABLE_NAME IN (
      'DIM_CUSTOMER', 'DIM_CREDIT_ACCOUNT', 'FACT_CUSTOMER_FINANCIAL_SNAPSHOT',
      'FACT_ACCOUNT_DAILY_SNAPSHOT', 'FACT_PAYMENT', 'FACT_CUSTOMER_CONTACT',
      'FACT_ACCOUNT_EVENT', 'FACT_DEFAULT_EVENT', 'ACCOUNT_OBSERVATION',
      'DEMO_CONFIG', 'PIPELINE_RUN', 'PROMOTION_DECISION'
    )
    AND TABLE_TYPE = 'BASE TABLE'
    AND NULLIF(TRIM(COMMENT), '') IS NULL
  UNION ALL
  SELECT 'COLUMN_COMMENTS_COMPLETE', COUNT(*) = 0
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_SCHEMA IN ('{{RAW_SCHEMA}}', '{{CONTROL_SCHEMA}}')
    AND TABLE_NAME IN (
      'DIM_CUSTOMER', 'DIM_CREDIT_ACCOUNT', 'FACT_CUSTOMER_FINANCIAL_SNAPSHOT',
      'FACT_ACCOUNT_DAILY_SNAPSHOT', 'FACT_PAYMENT', 'FACT_CUSTOMER_CONTACT',
      'FACT_ACCOUNT_EVENT', 'FACT_DEFAULT_EVENT', 'ACCOUNT_OBSERVATION',
      'DEMO_CONFIG', 'PIPELINE_RUN', 'PROMOTION_DECISION'
    )
    AND NULLIF(TRIM(COMMENT), '') IS NULL
)
SELECT IFF(BOOLOR_AGG(NOT COALESCE(PASSED, FALSE)), 'FAIL', 'PASS') AS PHASE_1_STATUS,
  ARRAY_AGG(IFF(NOT COALESCE(PASSED, FALSE), CHECK_NAME, NULL))
    WITHIN GROUP (ORDER BY CHECK_NAME)
    AS FAILED_CHECKS
FROM checks;

ALTER WAREHOUSE {{WAREHOUSE}} SUSPEND;