-- Additive control contracts. Do not rerun 01_bootstrap.sql to apply these.
-- Render with scripts/render_sql.py and review before authorised execution.

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE {{WAREHOUSE}};
USE DATABASE {{DATABASE}};

ALTER SCHEMA {{DATABASE}}.{{TEST_SCHEMA}} SET COMMENT =
  'Pre-Prod teaching schema for pipeline-release validation';
ALTER SCHEMA {{DATABASE}}.{{PROD_SCHEMA}} SET COMMENT =
  'Production-controlled candidates, serving selection and monitors';
ALTER SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}} SET COMMENT =
  'Portable project configuration and durable release evidence';

CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.TEST_FEATURE_STORE
  COMMENT = 'Pre-Prod Feature Store bindings; not the DEV Feature Store';
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.PROD_FEATURE_STORE
  COMMENT = 'Prod Feature Store bindings; training must not use DEV features';

GRANT USAGE ON SCHEMA {{DATABASE}}.{{TEST_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{PROD_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.TEST_FEATURE_STORE TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.TEST_FEATURE_STORE TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.TEST_FEATURE_STORE TO ROLE {{SERVICE_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.PROD_FEATURE_STORE TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.PROD_FEATURE_STORE TO ROLE {{PROD_OWNER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.PROD_FEATURE_STORE TO ROLE {{SERVICE_ROLE}};

GRANT CREATE TABLE, CREATE VIEW, CREATE DATASET, CREATE EXPERIMENT, CREATE MODEL,
      CREATE TAG, CREATE DYNAMIC TABLE
  ON SCHEMA {{DATABASE}}.{{TEST_SCHEMA}} TO ROLE {{ENGINEER_ROLE}};
GRANT CREATE TABLE, CREATE VIEW, CREATE DATASET, CREATE EXPERIMENT, CREATE MODEL,
      CREATE TAG, CREATE DYNAMIC TABLE
  ON SCHEMA {{DATABASE}}.{{PROD_SCHEMA}} TO ROLE {{ENGINEER_ROLE}};
GRANT CREATE TABLE, CREATE TAG, CREATE VIEW, CREATE DYNAMIC TABLE
  ON SCHEMA {{DATABASE}}.TEST_FEATURE_STORE TO ROLE {{ENGINEER_ROLE}};
GRANT CREATE TABLE, CREATE TAG, CREATE VIEW, CREATE DYNAMIC TABLE
  ON SCHEMA {{DATABASE}}.PROD_FEATURE_STORE TO ROLE {{ENGINEER_ROLE}};
GRANT CREATE CODE BUNDLE
  ON SCHEMA {{DATABASE}}.{{DEV_SCHEMA}} TO ROLE {{ENGINEER_ROLE}};
GRANT CREATE CODE BUNDLE
  ON SCHEMA {{DATABASE}}.{{TEST_SCHEMA}} TO ROLE {{ENGINEER_ROLE}};
GRANT CREATE CODE BUNDLE
  ON SCHEMA {{DATABASE}}.{{PROD_SCHEMA}} TO ROLE {{ENGINEER_ROLE}};

USE SCHEMA {{CONTROL_SCHEMA}};

CREATE TABLE IF NOT EXISTS SOURCE_RELEASE (
  RELEASE_ID VARCHAR COMMENT 'Immutable source-release identifier',
  SOURCE_COMMIT VARCHAR COMMENT 'Reviewed repository commit or source digest',
  PAYLOAD_DIGEST VARCHAR COMMENT 'Hash of the allowlisted release payload',
  MANIFEST_DIGEST VARCHAR COMMENT 'Hash of the frozen workflow contract',
  SPECIFICATION_DIGEST VARCHAR COMMENT 'Hash of the Code Bundle specification',
  RUNTIME_CONTRACT VARCHAR COMMENT 'Declared training runtime and dependencies',
  APPROVED_SOURCE_IDENTITY VARCHAR COMMENT 'Identity authorised for environment deployment',
  CREATED_BY VARCHAR COMMENT 'Principal that recorded the release',
  CREATED_AT TIMESTAMP_NTZ COMMENT 'Release-record timestamp'
) COMMENT = 'Immutable reviewed source identity for pipeline releases';

CREATE TABLE IF NOT EXISTS ENVIRONMENT_DEPLOYMENT (
  DEPLOYMENT_ID VARCHAR COMMENT 'Environment-specific deployment identifier',
  RELEASE_ID VARCHAR COMMENT 'Source release being deployed',
  ENVIRONMENT VARCHAR COMMENT 'DEV, TEST as Pre-Prod, or PROD',
  BINDING_DIGEST VARCHAR COMMENT 'Hash of environment bindings and configuration',
  BUNDLE_DATABASE VARCHAR COMMENT 'Database containing the deployed bundle',
  BUNDLE_SCHEMA VARCHAR COMMENT 'Schema containing the deployed bundle',
  BUNDLE_NAME VARCHAR COMMENT 'Release-specific Code Bundle name',
  DEPLOYED_BY VARCHAR COMMENT 'Principal that deployed the bundle',
  PIPELINE_VALIDATION_STATUS VARCHAR COMMENT 'Pre-Prod pipeline-release outcome when applicable',
  DEPLOYED_AT TIMESTAMP_NTZ COMMENT 'Deployment timestamp'
) COMMENT = 'Recorded binding of one source release to one environment';

CREATE TABLE IF NOT EXISTS PIPELINE_ATTEMPT (
  ATTEMPT_ID VARCHAR COMMENT 'Unique execution-attempt identifier',
  RUN_ID VARCHAR COMMENT 'Logical pipeline-run identifier shared across retries',
  RELEASE_ID VARCHAR COMMENT 'Source release executed by the attempt',
  DEPLOYMENT_ID VARCHAR COMMENT 'Environment deployment that supplied bindings',
  ENVIRONMENT VARCHAR COMMENT 'Effective environment for the attempt',
  EXECUTION_IDENTITY VARCHAR COMMENT 'Effective role or service identity',
  BUNDLE_NAME VARCHAR COMMENT 'Executed Code Bundle name when available',
  BUNDLE_QUERY_ID VARCHAR COMMENT 'Snowflake query identifier for bundle history',
  DATASET_NAME VARCHAR COMMENT 'Training Dataset name when resolved',
  DATASET_VERSION VARCHAR COMMENT 'Immutable Dataset version when resolved',
  FEATURE_CONTRACT VARCHAR COMMENT 'Pinned Feature View name and version contract',
  MODEL_DATABASE VARCHAR COMMENT 'Database of the registered candidate when present',
  MODEL_SCHEMA VARCHAR COMMENT 'Schema of the registered candidate when present',
  MODEL_NAME VARCHAR COMMENT 'Registered model collection name when present',
  MODEL_VERSION VARCHAR COMMENT 'Exact registered version when present',
  METRICS VARIANT COMMENT 'Structured screening metrics',
  EVIDENCE VARIANT COMMENT 'Structured evidence references',
  STATUS VARCHAR COMMENT 'accepted, rejected, failed, or running',
  FAILURE_DETAIL VARCHAR COMMENT 'Failure detail when no candidate was registered',
  STARTED_AT TIMESTAMP_NTZ COMMENT 'Attempt start timestamp',
  COMPLETED_AT TIMESTAMP_NTZ COMMENT 'Attempt completion timestamp'
) COMMENT = 'Durable training attempt; accepted is not live serving';

CREATE TABLE IF NOT EXISTS SERVING_SELECTION (
  SELECTION_ID VARCHAR COMMENT 'Serving-selection identifier',
  ENVIRONMENT VARCHAR COMMENT 'Environment whose callers resolve this selection',
  MODEL_DATABASE VARCHAR COMMENT 'Database of the approved model',
  MODEL_SCHEMA VARCHAR COMMENT 'Schema of the approved model',
  MODEL_NAME VARCHAR COMMENT 'Approved model collection name',
  MODEL_VERSION VARCHAR COMMENT 'Exact approved model version',
  FEATURE_CONTRACT VARCHAR COMMENT 'Compatible feature and inference contract',
  PREVIOUS_SELECTION_ID VARCHAR COMMENT 'Previous selection restored by recovery',
  DECISION_ID VARCHAR COMMENT 'Approval decision that authorised this selection',
  VERIFICATION_STATUS VARCHAR COMMENT 'Post-change smoke-test status',
  RECOVERY_STATUS VARCHAR COMMENT 'Recovery verification status when applicable',
  SELECTED_BY VARCHAR COMMENT 'Principal that changed the serving selection',
  SELECTED_AT TIMESTAMP_NTZ COMMENT 'Selection timestamp',
  ACTIVE BOOLEAN COMMENT 'Whether callers should resolve this selection'
) COMMENT = 'Explicit live-model selector; never implied by screening accepted';

GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.SOURCE_RELEASE
  TO ROLE {{DEVELOPER_ROLE}};
GRANT SELECT, INSERT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.SOURCE_RELEASE
  TO ROLE {{ENGINEER_ROLE}};
REVOKE UPDATE ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.SOURCE_RELEASE
  FROM ROLE {{ENGINEER_ROLE}};
GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.SOURCE_RELEASE
  TO ROLE {{PROD_OWNER_ROLE}};
GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.SOURCE_RELEASE
  TO ROLE {{SERVICE_ROLE}};

GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.ENVIRONMENT_DEPLOYMENT
  TO ROLE {{DEVELOPER_ROLE}};
GRANT SELECT, INSERT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.ENVIRONMENT_DEPLOYMENT
  TO ROLE {{ENGINEER_ROLE}};
REVOKE UPDATE ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.ENVIRONMENT_DEPLOYMENT
  FROM ROLE {{ENGINEER_ROLE}};
GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.ENVIRONMENT_DEPLOYMENT
  TO ROLE {{PROD_OWNER_ROLE}};
GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.ENVIRONMENT_DEPLOYMENT
  TO ROLE {{SERVICE_ROLE}};

GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.PIPELINE_ATTEMPT
  TO ROLE {{DEVELOPER_ROLE}};
GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.PIPELINE_ATTEMPT
  TO ROLE {{ENGINEER_ROLE}};
GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.PIPELINE_ATTEMPT
  TO ROLE {{PROD_OWNER_ROLE}};
GRANT SELECT, INSERT, UPDATE ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.PIPELINE_ATTEMPT
  TO ROLE {{SERVICE_ROLE}};
REVOKE INSERT, UPDATE ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.PIPELINE_ATTEMPT
  FROM ROLE {{ENGINEER_ROLE}};

GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.PROMOTION_DECISION
  TO ROLE {{ENGINEER_ROLE}};
GRANT SELECT, INSERT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.PROMOTION_DECISION
  TO ROLE {{PROD_OWNER_ROLE}};
REVOKE INSERT, UPDATE ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.PROMOTION_DECISION
  FROM ROLE {{SERVICE_ROLE}};
REVOKE INSERT, UPDATE ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.PROMOTION_DECISION
  FROM ROLE {{ENGINEER_ROLE}};
GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.PROMOTION_DECISION
  TO ROLE {{SERVICE_ROLE}};

GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.SERVING_SELECTION
  TO ROLE {{ENGINEER_ROLE}};
GRANT SELECT, INSERT, UPDATE ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.SERVING_SELECTION
  TO ROLE {{PROD_OWNER_ROLE}};
GRANT SELECT ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.SERVING_SELECTION
  TO ROLE {{SERVICE_ROLE}};
REVOKE INSERT, UPDATE ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.SERVING_SELECTION
  FROM ROLE {{ENGINEER_ROLE}};
REVOKE INSERT, UPDATE ON TABLE {{DATABASE}}.{{CONTROL_SCHEMA}}.SERVING_SELECTION
  FROM ROLE {{SERVICE_ROLE}};

SELECT 'CONTROL_CONTRACTS_READY' AS STATUS,
  '{{PREFIX}}' AS PREFIX,
  'TEST means Pre-Prod' AS TEACHING_NOTE;
