-- Portable bootstrap for the synthetic credit-default MLOps demo.
-- Render with scripts/render_sql.py and review before execution.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS {{DEVELOPER_ROLE}}
  COMMENT = 'Interactive development role for {{PREFIX}}';
CREATE ROLE IF NOT EXISTS {{ENGINEER_ROLE}}
  COMMENT = 'Deployment role for {{PREFIX}}';
CREATE ROLE IF NOT EXISTS {{PROD_OWNER_ROLE}}
  COMMENT = 'Production object owner for {{PREFIX}}';
CREATE ROLE IF NOT EXISTS {{SERVICE_ROLE}}
  COMMENT = 'Non-human execution role for {{PREFIX}}';

GRANT ROLE {{DEVELOPER_ROLE}} TO ROLE {{ENGINEER_ROLE}};
GRANT ROLE {{ENGINEER_ROLE}} TO ROLE {{PROD_OWNER_ROLE}};
GRANT ROLE {{PROD_OWNER_ROLE}} TO ROLE SYSADMIN;
GRANT ROLE {{SERVICE_ROLE}} TO ROLE {{PROD_OWNER_ROLE}};

CREATE WAREHOUSE IF NOT EXISTS {{WAREHOUSE}}
  WAREHOUSE_SIZE = {{WAREHOUSE_SIZE}}
  AUTO_SUSPEND = {{WAREHOUSE_AUTO_SUSPEND}}
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Disposable warehouse for {{PREFIX}}';
ALTER WAREHOUSE {{WAREHOUSE}} SET
  WAREHOUSE_SIZE = {{WAREHOUSE_SIZE}}
  AUTO_SUSPEND = {{WAREHOUSE_AUTO_SUSPEND}}
  AUTO_RESUME = TRUE;

CREATE COMPUTE POOL IF NOT EXISTS {{COMPUTE_POOL}}
  MIN_NODES = {{POOL_MIN_NODES}}
  MAX_NODES = {{POOL_MAX_NODES}}
  INSTANCE_FAMILY = {{POOL_INSTANCE_FAMILY}}
  AUTO_SUSPEND_SECS = {{POOL_AUTO_SUSPEND}}
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Disposable CPU pool for {{PREFIX}} ML Jobs';
ALTER COMPUTE POOL {{COMPUTE_POOL}} SET
  MIN_NODES = {{POOL_MIN_NODES}}
  MAX_NODES = {{POOL_MAX_NODES}}
  AUTO_SUSPEND_SECS = {{POOL_AUTO_SUSPEND}}
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS {{DATABASE}}
  COMMENT = 'Disposable synthetic credit-risk MLOps demo';
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{RAW_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{DEV_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{TEST_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{PROD_SCHEMA}};
CREATE SCHEMA IF NOT EXISTS {{DATABASE}}.{{CONTROL_SCHEMA}};

CREATE STAGE IF NOT EXISTS {{DATABASE}}.{{CONTROL_SCHEMA}}.{{RELEASE_STAGE}}
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Immutable release snapshots for {{PREFIX}}';
CREATE STAGE IF NOT EXISTS {{DATABASE}}.{{CONTROL_SCHEMA}}.{{JOB_STAGE}}
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'ML Job payloads for {{PREFIX}}';
CREATE STAGE IF NOT EXISTS {{DATABASE}}.{{CONTROL_SCHEMA}}.{{DAG_STAGE}}
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Task Graph payloads for {{PREFIX}}';

GRANT USAGE ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE, MONITOR ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE, MONITOR ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{PROD_OWNER_ROLE}};
GRANT USAGE, MONITOR ON WAREHOUSE {{WAREHOUSE}} TO ROLE {{SERVICE_ROLE}};
GRANT USAGE, MONITOR ON COMPUTE POOL {{COMPUTE_POOL}} TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE, MONITOR ON COMPUTE POOL {{COMPUTE_POOL}} TO ROLE {{PROD_OWNER_ROLE}};
GRANT USAGE, MONITOR ON COMPUTE POOL {{COMPUTE_POOL}} TO ROLE {{SERVICE_ROLE}};
GRANT EXECUTE TASK ON ACCOUNT TO ROLE {{PROD_OWNER_ROLE}};
GRANT EXECUTE TASK ON ACCOUNT TO ROLE {{SERVICE_ROLE}};

GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE ON ALL SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{PROD_OWNER_ROLE}};
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{PROD_OWNER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{DEV_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};

GRANT CREATE TABLE, CREATE VIEW, CREATE EXPERIMENT, CREATE MODEL
  ON SCHEMA {{DATABASE}}.{{DEV_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT CREATE SERVICE, CREATE TASK, CREATE NOTEBOOK PROJECT, CREATE MODEL MONITOR
  ON ALL SCHEMAS IN DATABASE {{DATABASE}} TO ROLE {{ENGINEER_ROLE}};
GRANT CREATE MODEL, CREATE MODEL MONITOR, CREATE TASK, CREATE VIEW, CREATE TABLE
  ON SCHEMA {{DATABASE}}.{{PROD_SCHEMA}} TO ROLE {{PROD_OWNER_ROLE}};
GRANT READ, WRITE ON ALL STAGES IN SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}}
  TO ROLE {{ENGINEER_ROLE}};
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}}
  TO ROLE {{ENGINEER_ROLE}};

USE WAREHOUSE {{WAREHOUSE}};
USE DATABASE {{DATABASE}};
USE SCHEMA {{RAW_SCHEMA}};

CREATE OR REPLACE TABLE ACCOUNT_SNAPSHOT AS
WITH accounts AS (
  SELECT
    ACCOUNT_ORDINAL + 1 AS ACCOUNT_NUMBER,
    'ACCT-' || LPAD((ACCOUNT_ORDINAL + 1)::VARCHAR, 7, '0') AS ACCOUNT_ID
  FROM (
    SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS ACCOUNT_ORDINAL
    FROM TABLE(GENERATOR(ROWCOUNT => {{ACCOUNT_COUNT}}))
  )
), months AS (
  SELECT
    MONTH_ORDINAL AS MONTH_NUMBER,
    DATEADD(MONTH, MONTH_ORDINAL, '{{FIRST_OBSERVATION_MONTH}}'::DATE) AS OBSERVATION_DATE
  FROM (
    SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) - 1 AS MONTH_ORDINAL
    FROM TABLE(GENERATOR(ROWCOUNT => {{OBSERVATION_MONTHS}}))
  )
), base AS (
  SELECT
    a.ACCOUNT_NUMBER,
    a.ACCOUNT_ID,
    m.MONTH_NUMBER,
    m.OBSERVATION_DATE,
    BITAND(HASH(a.ACCOUNT_NUMBER, {{DATA_SEED}}), 9223372036854775807) AS ACCOUNT_HASH,
    BITAND(HASH(a.ACCOUNT_NUMBER, m.MONTH_NUMBER, {{DATA_SEED}}), 9223372036854775807) AS MONTH_HASH
  FROM accounts a
  CROSS JOIN months m
)
SELECT
  ACCOUNT_ID,
  OBSERVATION_DATE,
  CASE MOD(ACCOUNT_HASH, 3)
    WHEN 0 THEN 'CREDIT_CARD'
    WHEN 1 THEN 'PERSONAL_LOAN'
    ELSE 'REVOLVING_CREDIT'
  END AS PRODUCT_TYPE,
  CASE MOD(FLOOR(ACCOUNT_HASH / 3), 3)
    WHEN 0 THEN 'BRANCH'
    WHEN 1 THEN 'DIGITAL'
    ELSE 'PARTNER'
  END AS ORIGINATION_CHANNEL,
  CASE
    WHEN 6 + MOD(ACCOUNT_HASH, 114) < 24 THEN 'UNDER_2Y'
    WHEN 6 + MOD(ACCOUNT_HASH, 114) < 60 THEN '2_TO_5Y'
    ELSE 'OVER_5Y'
  END AS TENURE_BAND,
  (6 + MOD(ACCOUNT_HASH, 114) + MONTH_NUMBER)::NUMBER(5,0) AS ACCOUNT_AGE_MONTHS,
  (1500 + MOD(ACCOUNT_HASH, 23500))::NUMBER(12,2) AS CREDIT_LIMIT,
  LEAST(
    1.25,
    GREATEST(
      0.01,
      0.16
      + MOD(MONTH_HASH, 5800) / 10000.0
      + IFF(OBSERVATION_DATE >= '{{DRIFT_START_DATE}}'::DATE, 0.11, 0)
      + 0.035 * SIN(MONTH_NUMBER / 3.0)
    )
  )::NUMBER(7,4) AS UTILISATION_RATIO,
  (900 + MOD(BITAND(HASH(ACCOUNT_NUMBER, {{DATA_SEED}} + 11), 9223372036854775807), 9100))::NUMBER(12,2)
    AS MONTHLY_INCOME_ESTIMATE,
  GREATEST(
    25,
    (120 + MOD(BITAND(HASH(ACCOUNT_NUMBER, MONTH_NUMBER, {{DATA_SEED}} + 17), 9223372036854775807), 1800))
      - IFF(OBSERVATION_DATE >= '{{DRIFT_START_DATE}}'::DATE, 70, 0)
  )::NUMBER(12,2) AS PAYMENT_AMOUNT_30D,
  IFF(
    MOD(BITAND(HASH(ACCOUNT_NUMBER, MONTH_NUMBER, {{DATA_SEED}} + 23), 9223372036854775807), 100)
      < 4 + IFF(OBSERVATION_DATE >= '{{DRIFT_START_DATE}}'::DATE, 3, 0),
    1,
    0
  )::NUMBER(1,0) AS MISSED_PAYMENT_30D,
  LEAST(
    3,
    IFF(MOD(BITAND(HASH(ACCOUNT_NUMBER, MONTH_NUMBER, {{DATA_SEED}} + 29), 9223372036854775807), 100) < 15, 1, 0)
      + IFF(MOD(BITAND(HASH(ACCOUNT_NUMBER, MONTH_NUMBER, {{DATA_SEED}} + 31), 9223372036854775807), 100) < 5, 1, 0)
      + IFF(OBSERVATION_DATE >= '{{DRIFT_START_DATE}}'::DATE
            AND MOD(BITAND(HASH(ACCOUNT_NUMBER, MONTH_NUMBER, {{DATA_SEED}} + 37), 9223372036854775807), 100) < 5, 1, 0)
  )::NUMBER(1,0) AS MISSED_PAYMENTS_6M,
  IFF(
    MOD(BITAND(HASH(ACCOUNT_NUMBER, MONTH_NUMBER, {{DATA_SEED}} + 41), 9223372036854775807), 100)
      < 6 + IFF(OBSERVATION_DATE >= '{{DRIFT_START_DATE}}'::DATE, 4, 0),
    1,
    0
  )::NUMBER(1,0) AS IN_ARREARS_30D,
  (MOD(BITAND(HASH(ACCOUNT_NUMBER, MONTH_NUMBER, {{DATA_SEED}} + 43), 9223372036854775807), 9))::NUMBER(2,0)
    AS CUSTOMER_CONTACTS_90D,
  IFF(OBSERVATION_DATE >= '{{DRIFT_START_DATE}}'::DATE, 'DRIFT', 'STABLE') AS DATA_SCENARIO,
  '{{AS_OF_DATE}} 00:00:00'::TIMESTAMP_NTZ AS GENERATED_AT
FROM base;

CREATE OR REPLACE TABLE DEFAULT_OUTCOME AS
WITH scored AS (
  SELECT
    s.*,
    -4.35
      + 2.30 * s.UTILISATION_RATIO
      + 0.95 * s.MISSED_PAYMENT_30D
      + 0.52 * s.MISSED_PAYMENTS_6M
      + 1.05 * s.IN_ARREARS_30D
      - 0.000055 * s.PAYMENT_AMOUNT_30D
      - 0.000025 * s.MONTHLY_INCOME_ESTIMATE
      + IFF(s.PRODUCT_TYPE = 'REVOLVING_CREDIT', 0.24, 0)
      + IFF(s.DATA_SCENARIO = 'DRIFT', 0.18, 0) AS LOG_ODDS,
    MOD(BITAND(HASH(s.ACCOUNT_ID, s.OBSERVATION_DATE, {{DATA_SEED}} + 97), 9223372036854775807), 1000000) / 1000000.0
      AS DRAW
  FROM ACCOUNT_SNAPSHOT s
)
SELECT
  ACCOUNT_ID,
  OBSERVATION_DATE,
  DATEADD(DAY, {{OUTCOME_WINDOW_DAYS}}, OBSERVATION_DATE)::DATE AS OUTCOME_FINALITY_DATE,
  IFF(DRAW < 1.0 / (1.0 + EXP(-LOG_ODDS)), 1, 0)::NUMBER(1,0) AS DEFAULT_WITHIN_90D,
  IFF(DATEADD(DAY, {{OUTCOME_WINDOW_DAYS}}, OBSERVATION_DATE) <= '{{AS_OF_DATE}}'::DATE,
      'FINALISED', 'PENDING') AS OUTCOME_STATUS,
  'Synthetic 90-day default outcome for technical demonstration only' AS OUTCOME_DEFINITION
FROM scored;

CREATE OR REPLACE VIEW AVAILABLE_GROUND_TRUTH AS
SELECT
  ACCOUNT_ID,
  OBSERVATION_DATE,
  OUTCOME_FINALITY_DATE,
  DEFAULT_WITHIN_90D
FROM DEFAULT_OUTCOME
WHERE OUTCOME_STATUS = 'FINALISED';

CREATE OR REPLACE VIEW TRAINING_BASE AS
SELECT
  s.ACCOUNT_ID,
  s.OBSERVATION_DATE,
  s.PRODUCT_TYPE,
  s.ORIGINATION_CHANNEL,
  s.TENURE_BAND,
  s.ACCOUNT_AGE_MONTHS,
  s.CREDIT_LIMIT,
  s.UTILISATION_RATIO,
  s.MONTHLY_INCOME_ESTIMATE,
  s.PAYMENT_AMOUNT_30D,
  s.MISSED_PAYMENT_30D,
  s.MISSED_PAYMENTS_6M,
  s.IN_ARREARS_30D,
  s.CUSTOMER_CONTACTS_90D,
  o.DEFAULT_WITHIN_90D,
  o.OUTCOME_FINALITY_DATE
FROM ACCOUNT_SNAPSHOT s
JOIN AVAILABLE_GROUND_TRUTH o
  USING (ACCOUNT_ID, OBSERVATION_DATE);

CREATE OR REPLACE VIEW SCORING_POPULATION AS
SELECT s.*
FROM ACCOUNT_SNAPSHOT s
JOIN DEFAULT_OUTCOME o
  USING (ACCOUNT_ID, OBSERVATION_DATE)
WHERE o.OUTCOME_STATUS = 'PENDING';

USE SCHEMA {{CONTROL_SCHEMA}};

CREATE OR REPLACE TABLE DEMO_CONFIG (
  CONFIG_KEY VARCHAR PRIMARY KEY,
  CONFIG_VALUE VARCHAR,
  DESCRIPTION VARCHAR
);

INSERT OVERWRITE INTO DEMO_CONFIG
SELECT column1, column2, column3
FROM VALUES
  ('PREFIX', '{{PREFIX}}', 'Safety prefix for account-level objects'),
  ('DATA_SEED', '{{DATA_SEED}}', 'Deterministic synthetic-data seed'),
  ('AS_OF_DATE', '{{AS_OF_DATE}}', 'Simulated information cutoff'),
  ('OUTCOME_WINDOW_DAYS', '{{OUTCOME_WINDOW_DAYS}}', 'Default outcome window'),
  ('DRIFT_START_DATE', '{{DRIFT_START_DATE}}', 'Start of controlled portfolio drift');

CREATE OR REPLACE TABLE PIPELINE_RUN (
  RUN_ID VARCHAR PRIMARY KEY,
  RELEASE_ID VARCHAR,
  ENVIRONMENT VARCHAR,
  STATUS VARCHAR,
  MODEL_NAME VARCHAR,
  MODEL_VERSION VARCHAR,
  SOURCE_COMMIT VARCHAR,
  METRICS VARIANT,
  DECISION_EVIDENCE VARIANT,
  STARTED_AT TIMESTAMP_NTZ,
  COMPLETED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE PROMOTION_DECISION (
  DECISION_ID VARCHAR PRIMARY KEY,
  RUN_ID VARCHAR,
  CANDIDATE_VERSION VARCHAR,
  INCUMBENT_VERSION VARCHAR,
  DECISION VARCHAR,
  CHECKS VARIANT,
  DECIDED_BY VARCHAR,
  DECIDED_AT TIMESTAMP_NTZ
);

GRANT SELECT ON ALL TABLES IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT SELECT ON ALL VIEWS IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT SELECT ON FUTURE TABLES IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT SELECT ON FUTURE VIEWS IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{DEVELOPER_ROLE}};
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}}
  TO ROLE {{ENGINEER_ROLE}};
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}}
  TO ROLE {{ENGINEER_ROLE}};
GRANT USAGE ON DATABASE {{DATABASE}} TO ROLE {{SERVICE_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{SERVICE_ROLE}};
GRANT USAGE ON SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}} TO ROLE {{SERVICE_ROLE}};
GRANT SELECT ON ALL TABLES IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{SERVICE_ROLE}};
GRANT SELECT ON ALL VIEWS IN SCHEMA {{DATABASE}}.{{RAW_SCHEMA}} TO ROLE {{SERVICE_ROLE}};
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA {{DATABASE}}.{{CONTROL_SCHEMA}}
  TO ROLE {{SERVICE_ROLE}};

-- Summarise the generated portfolio before releasing bootstrap compute.
SELECT
  COUNT(*) AS SNAPSHOT_ROWS,
  COUNT(DISTINCT ACCOUNT_ID) AS ACCOUNTS,
  MIN(OBSERVATION_DATE) AS FIRST_OBSERVATION,
  MAX(OBSERVATION_DATE) AS LAST_OBSERVATION,
  COUNT(DISTINCT OBSERVATION_DATE) AS OBSERVATION_MONTHS
FROM {{DATABASE}}.{{RAW_SCHEMA}}.ACCOUNT_SNAPSHOT;

SELECT
  COUNT(*) AS OUTCOME_ROWS,
  COUNT_IF(OUTCOME_STATUS = 'FINALISED') AS FINALISED_OUTCOMES,
  COUNT_IF(OUTCOME_STATUS = 'PENDING') AS PENDING_OUTCOMES,
  COUNT_IF(OUTCOME_STATUS = 'FINALISED' AND DEFAULT_WITHIN_90D = 1)
    AS FINALISED_DEFAULTS,
  AVG(IFF(OUTCOME_STATUS = 'FINALISED', DEFAULT_WITHIN_90D, NULL))
    AS FINALISED_DEFAULT_RATE,
  (SELECT COUNT(*) FROM {{DATABASE}}.{{RAW_SCHEMA}}.TRAINING_BASE)
    AS TRAINING_ROWS,
  (SELECT COUNT(*) FROM {{DATABASE}}.{{RAW_SCHEMA}}.SCORING_POPULATION)
    AS SCORING_ROWS
FROM {{DATABASE}}.{{RAW_SCHEMA}}.DEFAULT_OUTCOME;

SELECT
  s.DATA_SCENARIO,
  o.OUTCOME_STATUS,
  COUNT(*) AS SNAPSHOT_COUNT,
  AVG(s.UTILISATION_RATIO) AS AVG_UTILISATION_RATIO,
  AVG(s.MISSED_PAYMENT_30D) AS MISSED_PAYMENT_RATE_30D,
  AVG(s.MISSED_PAYMENTS_6M) AS AVG_MISSED_PAYMENTS_6M,
  AVG(s.IN_ARREARS_30D) AS ARREARS_RATE_30D,
  AVG(IFF(o.OUTCOME_STATUS = 'FINALISED', o.DEFAULT_WITHIN_90D, NULL))
    AS FINALISED_DEFAULT_RATE
FROM {{DATABASE}}.{{RAW_SCHEMA}}.ACCOUNT_SNAPSHOT s
JOIN {{DATABASE}}.{{RAW_SCHEMA}}.DEFAULT_OUTCOME o
  USING (ACCOUNT_ID, OBSERVATION_DATE)
GROUP BY s.DATA_SCENARIO, o.OUTCOME_STATUS
ORDER BY s.DATA_SCENARIO, o.OUTCOME_STATUS;

SELECT
  PRODUCT_TYPE,
  COUNT(*) AS SNAPSHOT_ROWS,
  COUNT(DISTINCT ACCOUNT_ID) AS ACCOUNTS,
  AVG(UTILISATION_RATIO) AS AVG_UTILISATION_RATIO,
  AVG(IN_ARREARS_30D) AS ARREARS_RATE_30D
FROM {{DATABASE}}.{{RAW_SCHEMA}}.ACCOUNT_SNAPSHOT
GROUP BY PRODUCT_TYPE
ORDER BY PRODUCT_TYPE;

ALTER WAREHOUSE {{WAREHOUSE}} SUSPEND;
ALTER COMPUTE POOL {{COMPUTE_POOL}} SUSPEND;

SELECT 'BOOTSTRAP_COMPLETE' AS STATUS, '{{DATABASE}}' AS DATABASE_NAME,
       '{{AS_OF_DATE}}'::DATE AS SIMULATED_AS_OF_DATE;