USE ROLE ACCOUNTADMIN;

SHOW DATABASES LIKE '{{DATABASE}}';
SHOW WAREHOUSES LIKE '{{WAREHOUSE}}';
SHOW COMPUTE POOLS LIKE '{{COMPUTE_POOL}}';
SHOW ROLES LIKE '{{DEVELOPER_ROLE}}';
SHOW ROLES LIKE '{{ENGINEER_ROLE}}';
SHOW ROLES LIKE '{{PROD_OWNER_ROLE}}';
SHOW ROLES LIKE '{{SERVICE_ROLE}}';
SHOW TASKS IN DATABASE {{DATABASE}};
SHOW NOTEBOOK PROJECTS IN DATABASE {{DATABASE}};
SHOW MODELS IN DATABASE {{DATABASE}};
SHOW MODEL MONITORS IN DATABASE {{DATABASE}};
SHOW EXPERIMENTS IN DATABASE {{DATABASE}};