USE ROLE ACCOUNTADMIN;
USE WAREHOUSE {{WAREHOUSE}};
USE DATABASE {{DATABASE}};

-- Expected: ACCOUNT_COUNT * OBSERVATION_MONTHS rows and one outcome per snapshot.
SELECT
  (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.ACCOUNT_SNAPSHOT) AS SNAPSHOT_ROWS,
  (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.DEFAULT_OUTCOME) AS OUTCOME_ROWS,
  {{ACCOUNT_COUNT}} * {{OBSERVATION_MONTHS}} AS EXPECTED_ROWS;

-- Review temporal coverage and ensure pending labels exist for the scoring demo.
SELECT
  MIN(OBSERVATION_DATE) AS FIRST_OBSERVATION,
  MAX(OBSERVATION_DATE) AS LAST_OBSERVATION,
  COUNT_IF(OUTCOME_STATUS = 'FINALISED') AS FINALISED_ROWS,
  COUNT_IF(OUTCOME_STATUS = 'PENDING') AS PENDING_ROWS,
  MIN(IFF(OUTCOME_STATUS = 'PENDING', OBSERVATION_DATE, NULL)) AS FIRST_PENDING_OBSERVATION
FROM {{RAW_SCHEMA}}.DEFAULT_OUTCOME;

-- Default prevalence should be imbalanced but large enough for evaluation.
SELECT
  DATE_TRUNC('YEAR', OBSERVATION_DATE) AS OBSERVATION_YEAR,
  COUNT(*) AS ROWS,
  AVG(DEFAULT_WITHIN_90D) AS DEFAULT_RATE
FROM {{RAW_SCHEMA}}.DEFAULT_OUTCOME
WHERE OUTCOME_STATUS = 'FINALISED'
GROUP BY 1
ORDER BY 1;

-- Controlled drift should be visible without making the target deterministic.
SELECT
  DATA_SCENARIO,
  COUNT(*) AS ROWS,
  AVG(UTILISATION_RATIO) AS AVG_UTILISATION,
  AVG(MISSED_PAYMENTS_6M) AS AVG_MISSED_PAYMENTS_6M,
  AVG(IN_ARREARS_30D) AS ARREARS_RATE
FROM {{RAW_SCHEMA}}.ACCOUNT_SNAPSHOT
GROUP BY 1
ORDER BY 1;

-- Operational segments only; no protected characteristics are generated.
SELECT
  PRODUCT_TYPE,
  ORIGINATION_CHANNEL,
  TENURE_BAND,
  COUNT(*) AS ROWS
FROM {{RAW_SCHEMA}}.ACCOUNT_SNAPSHOT
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3;

-- Pending outcomes must not leak into the training relation.
SELECT
  COUNT(*) AS TRAINING_ROWS,
  COUNT_IF(OUTCOME_FINALITY_DATE > '{{AS_OF_DATE}}'::DATE) AS NON_FINAL_TRAINING_ROWS
FROM {{RAW_SCHEMA}}.TRAINING_BASE;

-- Every account/date key must be unique.
SELECT ACCOUNT_ID, OBSERVATION_DATE, COUNT(*) AS DUPLICATES
FROM {{RAW_SCHEMA}}.ACCOUNT_SNAPSHOT
GROUP BY 1, 2
HAVING COUNT(*) > 1;

-- Machine-readable Phase 1 acceptance gate. All checks must pass before Phase 2.
WITH checks AS (
  SELECT 'EXPECTED_SNAPSHOT_ROWS' AS CHECK_NAME,
         (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.ACCOUNT_SNAPSHOT)
           = {{ACCOUNT_COUNT}} * {{OBSERVATION_MONTHS}} AS PASSED
  UNION ALL
  SELECT 'EXPECTED_OUTCOME_ROWS',
         (SELECT COUNT(*) FROM {{RAW_SCHEMA}}.DEFAULT_OUTCOME)
           = {{ACCOUNT_COUNT}} * {{OBSERVATION_MONTHS}}
  UNION ALL
  SELECT 'FINALISED_AND_PENDING_EXIST',
         COUNT_IF(OUTCOME_STATUS = 'FINALISED') > 0
           AND COUNT_IF(OUTCOME_STATUS = 'PENDING') > 0
  FROM {{RAW_SCHEMA}}.DEFAULT_OUTCOME
  UNION ALL
  SELECT 'NO_NON_FINAL_TRAINING_LABELS',
         COUNT_IF(OUTCOME_FINALITY_DATE > '{{AS_OF_DATE}}'::DATE) = 0
  FROM {{RAW_SCHEMA}}.TRAINING_BASE
  UNION ALL
  SELECT 'UNIQUE_SNAPSHOT_KEYS',
         COUNT(*) = COUNT(DISTINCT ACCOUNT_ID || '|' || OBSERVATION_DATE::VARCHAR)
  FROM {{RAW_SCHEMA}}.ACCOUNT_SNAPSHOT
  UNION ALL
  SELECT 'STABLE_AND_DRIFT_EXIST', COUNT(DISTINCT DATA_SCENARIO) = 2
  FROM {{RAW_SCHEMA}}.ACCOUNT_SNAPSHOT
  UNION ALL
  SELECT 'IMBALANCED_NONTRIVIAL_TARGET',
         AVG(DEFAULT_WITHIN_90D) BETWEEN 0.01 AND 0.25
  FROM {{RAW_SCHEMA}}.DEFAULT_OUTCOME
  WHERE OUTCOME_STATUS = 'FINALISED'
), result AS (
  SELECT CHECK_NAME, PASSED FROM checks
)
SELECT
  IFF(BOOLOR_AGG(NOT PASSED), 'FAIL', 'PASS') AS PHASE_1_STATUS,
  ARRAY_AGG(IFF(NOT PASSED, CHECK_NAME, NULL)) WITHIN GROUP (ORDER BY CHECK_NAME)
    AS FAILED_CHECKS
FROM result;

ALTER WAREHOUSE {{WAREHOUSE}} SUSPEND;